"""Manifest integrity checking in scripts/validate_gold.py.

Every test copies the committed gold files into a temp directory and points the
script there. Nothing reads a manifest from `data/gold/` and nothing writes to
it: the real manifest is generated by hand, and a test that could edit the gold
set would be a hole in the thing under test.

The three failure directions are separate tests because they are separate
failures — an edit, an addition that skipped regeneration, and a deletion the
per-file checks cannot see because there is no file left to check.
"""

from __future__ import annotations

import json
import shutil

import pytest
import validate_gold as vg
from validate_gold import (
    EXPECTED_GOLD_FILES,
    GOLD_DIR,
    MANIFEST_NAME,
    digest,
    main,
    manifest_problems,
    read_manifest,
)


@pytest.fixture
def gold(tmp_path, monkeypatch):
    """A writable copy of the gold set, with a manifest, wired into the script."""
    directory = tmp_path / "gold"
    directory.mkdir()
    for path in sorted(GOLD_DIR.glob("*.json"))[:EXPECTED_GOLD_FILES]:
        shutil.copy(path, directory / path.name)
    monkeypatch.setattr(vg, "GOLD_DIR", directory)
    monkeypatch.setattr(vg, "REPO_ROOT", tmp_path)
    assert main(["--write-manifest"]) == 0
    return directory


def test_the_copy_validates_before_anything_is_touched(gold) -> None:
    """The premise. Without it the three failure tests could pass for any reason."""
    assert main([]) == 0


def test_a_tampered_file_fails_and_names_both_digests(gold, capsys) -> None:
    """The case the manifest exists for: a record edited after it was labelled."""
    target = min(gold.glob("*.json"))
    recorded = read_manifest(gold / MANIFEST_NAME)[target.name]
    document = json.loads(target.read_text())
    document["experiments"][0]["organism"]["confidence"] = "low"
    target.write_text(json.dumps(document, indent=2))

    assert main([]) == 1

    out = capsys.readouterr().out
    assert target.name in out
    assert recorded in out, "the message does not name the digest the manifest recorded"
    assert digest(target) in out, "the message does not name the digest found on disk"


def test_a_file_absent_from_the_manifest_fails(gold) -> None:
    """An addition that skipped regeneration is not silently blessed."""
    source = min(gold.glob("*.json"))
    shutil.copy(source, gold / "zz_added.json")

    assert main([]) == 1


def test_a_manifest_entry_whose_file_is_gone_fails(gold) -> None:
    """A deletion. No file remains, so no per-file check can see it."""
    doomed = min(gold.glob("*.json"))
    doomed.unlink()

    # The floor would also catch this one; drop it so the manifest check is
    # unambiguously the thing that fires.
    monkeypatched = EXPECTED_GOLD_FILES - 1
    with pytest.MonkeyPatch.context() as patch:
        patch.setattr(vg, "EXPECTED_GOLD_FILES", monkeypatched)
        assert main([]) == 1


def test_every_direction_is_reported_at_once(gold) -> None:
    """One run names all of them, rather than stopping at the first."""
    files = sorted(gold.glob("*.json"))
    files[0].write_text(json.dumps({"schema_version": "0.4.0", "experiments": []}))
    shutil.copy(files[1], gold / "zz_added.json")
    files[2].unlink()

    entries = read_manifest(gold / MANIFEST_NAME)
    problems = manifest_problems(sorted(gold.glob("*.json")), entries)

    kinds = {
        "changed": any("does not match" in p for p in problems),
        "added": any("absent from" in p for p in problems),
        "removed": any("missing from" in p for p in problems),
    }
    assert all(kinds.values()), kinds


def test_a_malformed_manifest_line_is_refused_not_skipped(gold) -> None:
    """A partly-unreadable manifest protects only the part that parsed."""
    manifest = gold / MANIFEST_NAME
    manifest.write_text(manifest.read_text() + "not-a-digest  stray.json\n")

    assert main([]) == 1


def test_a_missing_manifest_fails_rather_than_passing_quietly(gold) -> None:
    """No manifest is not the same as nothing to check."""
    (gold / MANIFEST_NAME).unlink()

    assert main([]) == 1


def test_the_manifest_is_shasum_verifiable(gold) -> None:
    """Standard format, so the human can audit it without this script.

    The point of `<hex>  <name>` is that `shasum -a 256 -c` reads it. If this
    drifts to JSON or to a single-space separator, the independent check the
    format exists to allow stops working.
    """
    for line in (gold / MANIFEST_NAME).read_text().splitlines():
        hexdigest, separator, name = line.partition("  ")
        assert separator == "  ", f"not two spaces: {line!r}"
        assert len(hexdigest) == 64 and all(c in "0123456789abcdef" for c in hexdigest)
        assert (gold / name).is_file()


def test_the_manifest_does_not_list_itself(gold) -> None:
    """It cannot: its own digest changes as it is written."""
    assert MANIFEST_NAME not in read_manifest(gold / MANIFEST_NAME)
